---
title: CV
format:
  quarto-cv-pdf: default
author: Shune Kawaoto
date: last-modified
email: kawaotoshune@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: shunekawaoto2003
# orcid: 0000-0002-1825-0097
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
web: shunekawaoto.netlify.app
fontawesome: yes
nocite: '@*'
validate-yaml: false
---

<!-- # Employment -->

<!-- *Arthur Guinness & Son* -->

<!-- Chief Brewer (Park Royal) \hfill 1935-1937 -->

<!-- Researcher (Dublin) \hfill 1899-1935 -->

# Education
*University of California, Los Angeles*, B.S. Statistics and Data Science \hfill 2021 - 2024

# Work Experience
- Statistical Consultant \hfill April 2024 - June 2024
  - *UCLA*
- University Apartment Mailroom Worker \hfill August 2023 - June 2024
  - *UCLA Housing*
- Bussing Supervisor \hfill September 2022 - July 2023
  - *Ackerman Student Union*
- Copy Editor \hfill September 2021 - June 2024
  - *Pacific Ties Newsmagazine*

# Coursework
- STATS 20 \hfill Introduction to Statistical Programming with R
- STATS 100A \hfill Introduction to Probability
- STATS 100B \hfill Introduction to Mathematical Statistics
- STATS 100C \hfill Linear Models
- STATS 101A \hfill Introduction to Data Analysis and Regression
- STATS 101B \hfill Introduction to Design and Analysis of Experiment
- STATS 101C \hfill Introduction to Statistical Models and Data Mining
- STATS 102A \hfill Introduction to Computational Statistics with R
- STATS 102B \hfill Introduction to Computation and Optimization for Statistics
- STATS 102C \hfill Introduction to Monte Carlo Methods
- STATS C155 \hfill Applied Sampling
- STATS C173 \hfill Applied Geostatistics
- COM SCI 31 \hfill Introduction to Computer Science I
- COM SCI 32 \hfill Introduction to Computer Science II
- MATH 115A \hfill Linear Algebra
- MATH 131A \hfill Analysis
- GEOG 7 \hfill Introduction to Geographic Information Systems

# Projects
- **[Predicting Electric Vehicle Prices](https://github.com/shunekawaoto2003/Predicting-EV-Prices)**
  - Created a linear model to predict the price of EV vehicles based on their configurations such as top speed, 
  mileage, charge speed, etc.
- **[Predicting the Alcoholic Status of Individuals From Health Data](https://github.com/shunekawaoto2003/Predicting-Alcoholic-Status)**
  - Used machine learning models to impute and predict individuals' alcoholic statuses with a 73% predicting rate.
- **[Analysis of Lighting Conditions Affecting Perception of Photos](https://github.com/shunekawaoto2003/Analysis-of-light-conditions)**
  - Used a random forest model to predict how different lighting conditions affects the perceptions of photos.

# Technical Experience
C++, R, Python, SQL, Excel, Stata, GIS

